### PR TITLE
Rollforward to pouch-vue v0.3.4 and other fixes

### PR DESCRIPTION
**Pull request by assemblethis**
Hello,

I've been collaborating on the [pouch-vue project](https://github.com/MDSLKTR/pouch-vue) and started taking a look at your boatnet project which is very well done. I like the structure of how you're using pouch in your PWA with the vuex modules and the service layer so I have been testing it out in my own PWA project. This PR is a copy&paste of what is working for me in my own project since I'm not actually developing on your repo, just using it for ideas. So I've included a number of fixes which hopefully are of use to your project and compile properly.

In pouch-vue v0.3.4, we have fixed a bug with the 'paused' event in pouchdb sync that I think was being alluded to in your code here:

https://github.com/nwfsc-fram/boatnet/blob/a79f4f47aa7d2b9f4ef67f53b2bd3c00be16ee32/libs/bn-pouch/src/_services/pouch.service.ts#L150-L161

So I went ahead and remove your workaround for the bug after rolling forward the version of pouch-vue that boatnet uses to v0.3.4 which has a fix for the bug and is the latest version.

I also cleaned up the typescript a bit since there's been changes to interface names in pouch-vue and the plugin pouchdb-live-find now has its own typings on DefinitelyTyped as well, so no need for the @ts-ignore comments anymore.

I've seen a few comments about authentication issues that Boatnet has had:

https://github.com/nwfsc-fram/boatnet/blob/c1146306cd959ac824dfa5e2a02915f68b035417/libs/bn-pouch/src/_services/pouch.service.ts#L84

For me these were fixed by overriding the fetch method and so I've included that commit as well.

In the Vuex store for the pouch module I moved the async connect methods out of the mutations section and into the actions section where I think they belong.

I've included detailed comments with each of the commits. Let me know what you think.

Thanks for sharing your work on github. It's been very interesting to go through!

### CODE REVIEW

**Comment by wsmith-nwfsc** [comment]
@assemblethis thank you for the thoughtful writeup and for the PR! We're just getting started in the Vue world and your work with pouch-vue has already been extremely useful. I'll merge this when I get some quality time to look over your enhancements. What a pleasant surprise, thanks from the team!

**Comment by wsmith-nwfsc** [comment]
I cleared my node_modules, nuked yarn.lock and yarn cache, re-installed pouch-vue v0.3.4 and pouchdb-browser v7.0.0, installed 
"@types/pouchdb-live-find": "^0.4.0", and pouchdb-live-find, and I still can't seem to get around this:
```
ERROR in C:/git/boatnet/libs/bn-pouch/src/_services/pouch.service.ts
10:20 Module '"../../../../node_modules/pouch-vue/types"' has no exported member 'PouchAPI'.
     8 | import plf from 'pouchdb-live-find';
     9 | import pa from 'pouchdb-authentication';
  > 10 | import PouchVue, { PouchAPI } from 'pouch-vue';
```
(The path is a little "interesting" because we use Lerna for a monorepo approach.) 
I see the types declared in pouch-vue/types, it just chokes on my end for some reason.
I'll give it another shot later, as these improvements will be nice to roll in!

**Comment by assemblethis** [comment]
Hi Will, I removed the reference to 'PouchAPI' since it wasn't being used now that the augmentation to the Vue instance properties have been moved to the pouch-vue type declaration.

Hopefully that works! Let me know if there's any other issues.

**Comment by assemblethis** [comment]
Hi Will, if you rollforward to pouchdb v7.1.1 (June 13, 2019) there's a fix for an auth issue where credentials weren't being included for fetch when the request was cross-domain, just xhr requests had credentials included. The workaround with v7.0 was to override the fetch function to include credentials, but this is no longer necessary. So I removed the fetch override in case you were updating to pouchdb v7.1.1 at some point. I left a link to further information about this in the last commit.

**Comment by wsmith-nwfsc** [comment]
Great, thanks for the update @assemblethis . We're sidetracked on some other stuff at the moment, but looking forward to rolling in your improvement one of the days soon.

**Comment by wsmith-nwfsc** [comment]
Dusting this off, #1127

**Comment by wsmith-nwfsc** [comment]
Finally merged this! :)

**Pull request closed without merging**
