### PR TITLE
obs-web: debriefer column select styling

### PR DESCRIPTION
**Pull request by sethgerou-noaa**
@Mak-NOAA @toddhay-NOAA 
Todd and I were chatting about the look of the select, and thought it looked a little rough with all options selected, so I looked into disabling showing the selected options, and adding icons to selected options in the dropdown.

### CODE REVIEW

**Comment by toddhay-NOAA** [comment]
looks great @sethgerou-noaa , thanks for doing this.

**Comment by toddhay-NOAA** [comment]
one final request on this.  For the list of names in the drop down list, it looks like we have the model attributes listed, instead of the display names for the actual columns, anyway of showing the display names instead?

**Comment by Mak-NOAA** [comment]
@sethgerou-noaa  per Todd's last request is that complete too? I'm thinking this ticket should be marked as Done right?

**Comment by sethgerou-noaa** [comment]
Still wrapping up Todd's latest request.  Should have it done in a few minutes.

**Comment by Mak-NOAA** [comment]
Cool thanks

**Comment by sethgerou-noaa** [comment]
OK, it's done now.

**Comment by toddhay-NOAA** [comment]
this looks great @sethgerou-noaa , thanks for doing this.  I'm closing out this ticket.

**Pull request merged**
