### PR TITLE
adding a multi select dropdown for visible columns

### PR DESCRIPTION
**Pull request by Mak-NOAA**
@sethgerou-noaa  I tried to add a multi select dropdown (https://v1.quasar-framework.org/vue-components/select#The-model) to allow the user to control visible columns but somehow the toggle switches disappeared and the select list doesn't even show. I don't even know how to debug why they disappeared, any advice?

### CODE REVIEW

**Comment by toddhay-NOAA** [comment]
@Mak-NOAA , I think the better quasar widgets for this would be two lists:

https://v1.quasar-framework.org/vue-components/list-and-list-items

**Comment by Mak-NOAA** [comment]
@toddhay-NOAA I don't see any dragging capability between two lists. Are you saying a user clicks on a column in one list and it pops over to the 2nd list? I think a multi select dropdown is more intuitive and all in one place

**Comment by toddhay-NOAA** [comment]
@Mak-NOAA , I guess I was not anticipating a drag/drop between the two lists, but rather arrow keys between them for moving contents back and forth.  However, having said that, I like your idea of using the multi-select dropdown.  Let's try that for now and we'll see how the users like it.

**Comment by Mak-NOAA** [comment]
@toddhay-NOAA sounds good

**Comment by sethgerou-noaa** [comment]
After Mak merges my changes, take a look at the (working) multi-select.  

It's intuitive, fast, doesn't take up the space that a multi-select (two lists + controls) does, and probably most importantly, doesn't require building a custom component.

**Comment by Mak-NOAA** [comment]
@sethgerou-noaa that's exactly what I was trying to do....thank you :) 
@toddhay-NOAA check it out, it looks good

**Pull request merged**
