### PR TITLE
Debriefer hauls page

### PR DESCRIPTION
**Pull request by Mak-NOAA**
@sethgerou-noaa this code is not working. Any advice on refactoring? I tried to use the import component from the forums.

@wsmith-nwfsc @toddhay-NOAA if you have thoughts.

### CODE REVIEW

**Comment by sethgerou-noaa** [comment]
My suggestion would be to create a component for each tab of the Debriefer page, which would include the template code and the functions required to fill the template.

Best example I have is on **UserConfig.vue**...
you'll see in the template, all the content actually comes from another component - **app-user-details**
(note: there isn't anything else on this page at the moment, so this architecture seems pointless, but it's intended to be a single page for all user configuration, which may include user details, and also other configuration tbd)

I wanted user details to be available from multiple places in the app, so I
**import UserDetails from './views/UserDetails.vue';**
in **main.ts**, but I could have done that on **UserDetails.vue** just as well

An important thing to note, all of the template and code that populates **app-user-details**, resides in **UserDetails.vue**, and not on the **UserConfig.vue** page that uses the component.

You'll probably want to store debriefer trips info in a vuex store so you have access to it on the other tabs/components.  An example:

On my **UserDetails** page you'll see:
**import { GeneralState, UserState, VesselState } from '../_store/types/types';**
and
**@State('user') private user!: UserState;**

once that state is properly configured, you can reference in the template with user.attribute, and in the ts code with this.user.attribute

How state is configured:
In the **_store** directory, you'll see **user.module.ts**, which defines an array users, and a newUser boolean that can shared by any component that uses this portion of state.
note the namespacing boilerplate, it's important.

In **index.ts**:
the module is imported and added to the app store modules

Typing for the store is defined in **_store/types/types.ts**:
**export interface UserState {
  activeUser?: Person;
  users: Person[];
  newUser: boolean;
}**

Take a look at all that stuff and let me know what questions you have.

**Comment by Mak-NOAA** [comment]
Thanks @sethgerou-noaa , I'm still digesting your comment....it's a little overwhelming :)

**Comment by Mak-NOAA** [comment]
@sethgerou-noaa I can imagine having components for the scripts but don't know how we would break up the template code? how do I include a template within a template from another file?

How does UserConfig.vue know about UserDetails app-user-details template....is it because you put it in main.ts as you mentioned? You have it in there as "Vue.component('appUserDetails', UserDetails);" so I wonder if I can do Vue.component('appUserDetails', UserDetails) somehow within my Debriefer.vue

**Comment by sethgerou-noaa** [comment]
yes, by putting Vue.component('appUserDetails', UserDetails); in main.ts, I can now use the component in any template as <app-user-details></app-user-details>  - as in line 4 of UserConfig.vue

**Pull request merged**
