### PR TITLE
Adding catch tab info #296

### PR DESCRIPTION
**Pull request by Mak-NOAA**
@sethgerou-noaa @wsmith-nwfsc @NickShafferNOAA @toddhay-NOAA 
I'm having trouble grabbing the species info using the all-operations view. As you can see the catches field on the operations view doesn't contain species information but when I go to couchdb and click on the json tab for the all-operations view, I do see species information. Any thoughts?

Screen Shot 2019-06-03 at 10 08 58 PM
Screen Shot 2019-06-03 at 10 11 11 PM

### CODE REVIEW

**Comment by toddhay-NOAA** [comment]
@Mak-NOAA , are you sure that it might not just be that particular wcgop-catch record that does not have any species?  Are all of them lacking species?

**Comment by toddhay-NOAA** [comment]
One other comment @Mak-NOAA , so in that Debrier.vue file, you're approaching 500 lines of code.  I wonder if we shouldn't separate the contents of each tab into their own components that are stored in separate *.vue files to try and keep the lines of code down?

**Comment by Mak-NOAA** [comment]
@toddhay-NOAA I double checked a bunch of random catches and still the same issue. 
As far as refactoring, the plan is to do that once all the tabs are created.

@sethgerou-noaa / @wsmith-nwfsc / @NickShafferNOAA what are your thoughts on the data?

**Comment by NickShafferNOAA** [comment]
@Mak-NOAA As Todd mentioned, my initial thought is simply that that record has no species, and thus the property wouldn't exist. If that's not the case, it would be helpful to share with me the legacy section of the document in question (to see the old IDs) so I can do some digging and see if there is a problem on the raw data side of things.

**Comment by Mak-NOAA** [comment]
@wsmith-nwfsc / @sethgerou-noaa can you check if the code looks right?
@NickShafferNOAA I'm gonna get you some legacy section data to investigate

**Comment by sethgerou-noaa** [comment]
the last line of the catch template isn't going to work as catch.species is an array you need to iterate over to either break into individual rows, or aggregate for display.

line 318 <q-td key="catchSpecies" :props="props">{{ props.row.catch.species.species.commonName }}</q-td>

(To display a list of species common names) you could do something like:
<q-td key="catchSpecies" :props="props">{{ getCommonName(props.row) }}</q-td>

private getCommonName(row: any) {
  if (row.catch && row.catch.species) {
    let returnString = '';
    for (const species of row.catch.species) {
       returnString += species.species.commonName + ', ';
   }
    return returnString;
  } else {
    return ''
  }
}

**Comment by Mak-NOAA** [comment]
Thanks @sethgerou-noaa makes sense

**Pull request merged**
