### PR TITLE
Added EM Review page to obs-web

### PR DESCRIPTION
**Pull request by melinashak-noaa**

### CODE REVIEW

**Review by sethgerou-noaa — APPROVED** [review]
looks good!

**Comment by neilriley-NOAA** [comment]
@melinashak-noaa Looks good.  Excited to check it out as we get more test data submitted.

**Comment by neilriley-NOAA** [comment]
@melinashak-noaa I know this page is only displaying data submitted via the provider. I do wonder if we will need to display the descriptions for a couple of these fields along side the code, such as the species common name. I am sure there will be users who will not know all the codes won't want to look them up each time.

**Comment by melinashak-noaa** [comment]
True, good point

**Comment by neilriley-NOAA** [comment]
If we can display the common name in a column next to the species code, I think we should.

**Pull request merged**
